version: "2"

run:
  timeout: 3m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nilerr
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
